name: Deploying Node.js App on EC Server

on:
  push:
    branches:
        - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{secrets.EC2_HOST}}
            username: ${{secrets.EC2_USER}}
            key: ${{secrets.EC2_KEY}}
            script: |
              APP_DIR=/home/ubuntu/app
              if [ ! -d "$APP_DIR" ]; then
              git clone https://github.com/ShusilLimbu/earbud_store.git $APP_DIR
              fi
              cd $APP_DIR
              git pull origin main
              printf "PORT=${{ secrets.PORT }}\nMONGO_URI=${{ secrets.MONGO_URI }}\nJWT_SECRET=${{ secrets.JWT_SECRET }}\n" > .env
              docker compose down || true
              docker compose up -d --build